name: CI (Linux)

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable

      - name: rustfmt
        run: cargo fmt --all -- --check

      - name: check
        run: cargo check --all --bins --examples --tests

      - uses: actions/setup-java@v5
        with:
          distribution: "zulu" # See 'Supported distributions' for available options
          java-version: "21"

      - name: tests
        timeout-minutes: 40
        run: cargo test --all --no-fail-fast -- --nocapture

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable

      - name: doc
        env:
          RUSTDOCFLAGS: -Dwarnings
        run: cargo doc --all --no-deps

  publish:
    name: Publish Package
    needs: [build_and_test, doc]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - name: login
        env:
          SUPER_SECRET: ${{ secrets.CARGO_TOKEN }}
        run: cargo login "$SUPER_SECRET"

      - name: publish
        run: cargo publish
